### ISSUE TITLE
Need more info

### ISSUE THREAD

**Issue by glolsh** [unsacrificed/network-list-parser#2]
Hello! I'm trying to build .bin file on one of hetzner cloud solutions. And it keeps throwing errors at me.
I use ubuntu 18.04
For starters I assumed that I need golang package (of course).
After that it started throwing this:
`can't load package: package github.com/unsacrificed/network-list-parser: cannot find package "github.com/unsacrificed/network-list-parser" in any of:
        /usr/lib/go-1.10/src/github.com/unsacrificed/network-list-parser (from $GOROOT)
        /home/vpnuser/go/src/github.com/unsacrificed/network-list-parser (from $GOPATH)
darwin amd64
can't load package: package github.com/unsacrificed/network-list-parser: cannot find package "github.com/unsacrificed/network-list-parser" in any of:
        /usr/lib/go-1.10/src/github.com/unsacrificed/network-list-parser (from $GOROOT)
        /home/vpnuser/go/src/github.com/unsacrificed/network-list-parser (from $GOPATH)
dragonfly amd64
can't load package: package github.com/unsacrificed/network-list-parser: cannot find package "github.com/unsacrificed/network-list-parser" in any of:
        /usr/lib/go-1.10/src/github.com/unsacrificed/network-list-parser (from $GOROOT)
        /home/vpnuser/go/src/github.com/unsacrificed/network-list-parser (from $GOPATH)
freebsd 386
can't load package: package github.com/unsacrificed/network-list-parser: cannot find package "github.com/unsacrificed/network-list-parser" in any of:
        /usr/lib/go-1.10/src/github.com/unsacrificed/network-list-parser (from $GOROOT)
        /home/vpnuser/go/src/github.com/unsacrificed/network-list-parser (from $GOPATH)
freebsd amd64
`
I could've fixed that myself (with my "guess-try-repeat"), but I don't get what you're trying to do there. Some comments would help. Thank you!

**Comment by anton-becker** [comment]
Hi.
Which command causes this output? build-for-all.sh?

**Comment by glolsh** [comment]
Yeah. Strictly speaking: bash build-for-all.sh

**Comment by anton-becker** [comment]
There are 2 ways to get network-list-parser:
 1) Download binary for your platform from [Releases](https://github.com/unsacrificed/network-list-parser/releases). This binary is ready-2-use: no GoLang required on target platform, no other dependencies (statically builded).
 2) Compile from source as any other program on GoLang. This way is slightly harder. 

**Compile from source in short:**
 1) Get, install & configure (if required) GoLang using your package manager or [golang.org](https://golang.org/dl/) 
 2) run `go get github.com/unsacrificed/network-list-parser` - this will fetch required sources and build binary in "$GOPATH" (smth. like `~/go/bin/network-list-parser`).

**Comment by anton-becker** [comment]
Do not use `build-for-all.sh` - is a script which build binaries for all available platforms and archs when I public release. "for-all" is "for all platforms and archs", not "for everybody".

**Comment by glolsh** [comment]
Thank you. Then I'll use .bin from Releases.
