### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by glolsh** [unsacrificed/network-list-parser#3]
I'm reading doc.go and there is "." symbol under Usage section. Am I missing something? How to use it?
I found command on habr.com which I adapted to
`./network-list-parser-linux-amd64-1.2.bin -src-file dump.csv -dst-file list.txt -prefix "/ip firewall address-list add address=" -suffix " list=RKN"`
But I want to try different options if there are any.

**Comment by anton-becker** [comment]
`doc.go` just program description.
Use `network-list-parser -h` to view description & usage (program args).

**Comment by glolsh** [comment]
And again, thank you very much.
